# Site settings
title: Cloude Resume Challenge, AWS Cloud Engineer
tag_text: Cloud
description: The Cloud Resume Challenge.
# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
