# Site settings
title: Cloude Resume Challenge, AWS Cloud Engineer
tag_text: Cloud
description: The Cloud Resume Challenge is a hands-on project designed to help you bridge the gap from cloud certification to cloud job.

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
